### PR TITLE
start implementing majorana metrics

### PR DESCRIPTION
**Pull request by williamesamuelson**

### CODE REVIEW

**Comment by williamesamuelson** [comment]
Does it make sense to restrict the Hamiltonian as much as I do now @cvsvensson? It just seemed like this would make implementing the quality metrics easier, and I felt like parity conservation is something one should have in Majorana-related problems. 

Also, I guess you see my problem of having to store the basis twice.

**Comment by cvsvensson** [comment]
It makes sense to start with the case we are most interested in and get that working. If we want something else in the future, we can tackle that then.

I forgot that we had the struct DiagonalHamiltonian. I guess one could actually just use a single field for the hamiltonian then. Like:
```julia
ham::Union{BlockDiagonal, DiagonalizedHamiltonian}
basis::B
```

This could be more general. One could have a type `ArrayWithBasis{T,N,B}` which just stores an `<:AbstractArray{T,N}` and a basis `B`. Then states and operators could carry around the basis by themselves. I've resisted doing this, because I want the objects returned from QuantumDots to be as primitive and simple as possible. But it might make sense to test that out here.

**Comment by cvsvensson** [comment]
If you want to avoid some duplicate computation, you could also put a dict into the struct that stores results. Then one could for example store the quantities from `energy_info` as key value pairs there. When the user calls a function with the Hamiltonian as an argument, one can check if the dict contains some relevant key; if it does, reuse the value, if it doesn't, compute it and store it.

In that case, one could also store the diagonalized hamiltonian there, and then the struct can be immutable instead.

The advantage of this is that it is very easy to store and reuse any new quantity one thinks of. The disadvantage is that the struct is not so tightly defined. But since there are lots of different things one may want to calculate given a Hamiltonian, perhaps flexibility is the most important thing here.

**Comment by williamesamuelson** [comment]
That sounds like a good idea. I'll try it out.

**Comment by williamesamuelson** [comment]
Is this sort of what you meant?

**Comment by cvsvensson** [comment]
After you've registered the new version in your registry, you can go to github `Actions -> TagBot -> run workflow` to get a tagged release here on github.

**Pull request merged**
